### ISSUE TITLE
Can't get venv up

### ISSUE THREAD

**Issue by njmurarka** [Echolon166/bluzelle_bot#1]
Tried to do the first step in the process of setting up the bot to run, on an Ubuntu 20.04 box, and got the following:

python -m venv venv

Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python' from deb python-is-python3

Please outline all the steps to get the environment setup properly. It will save time and increase the chances of winning. We may not have expertise in the languages and environment you have. 

This means all dependencies, etc... 

We tried to install Python on our own but then ran into other issues such as pip and venv missing and pip could not be installed as the version of Python that got installed was incorrect...

Do we need to use "python" or "python3"? Not sure.

**Comment by njmurarka** [comment]
We got it to work after switching over to Python3 and manually installing all the dependencies. Please update the docs to show these steps... would appreciate it.

**Comment by Echolon166** [comment]
Updated README to include setting up development environment.
